### ISSUE TITLE
String Comparison Crash

### ISSUE THREAD

**Issue by saru2020** [krisk/fuse-swift#18]
Hi,

Is there any reason why the below line of string comparison would lead to a crash?

        let result = fuse.search("Rancheras 2016 Borracho de Amor  Por Tu Maldito Amor  Hermoso Carino  Se Va Muriendo Mi Alma  Por un Amor", in: "Borracho De Amor")

<img width="853" alt="fuse - comparison" src="https://user-images.githubusercontent.com/1034916/50790786-df9e1200-12e5-11e9-9b7b-8693714d1f0e.png">
<img width="854" alt="fuse - crash" src="https://user-images.githubusercontent.com/1034916/50790788-df9e1200-12e5-11e9-9753-9d68c3f9c66d.png">

Any help would be appreciated. Thanks!

**Comment by krisk** [comment]
Oooh, the string may simply be too long.

**Comment by krisk** [comment]
You have the arguments the other way around.

Your pattern is the first argument, and the string you are searching in is your second.

See [here](https://github.com/krisk/fuse-swift/blob/master/Fuse/Classes/Fuse.swift#L101) for reference.

**Comment by adamcichy** [comment]
@krisk The same bug happens randomly for me when the pattern is longer than the string (which happens often in my case but works fine most of the time). Should I prevent such usecase in my code? O is there going to be a release that will handle this case?
