### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by abiaad** [krisk/fuse-swift#19]
Hello,

Would be nice to support Carthage. WDYT ? 🙂

**Comment by krisk** [comment]
I think it would indeed be good. Wanna take a stab at it? 😄

**Comment by abiaad** [comment]
I'll have a look 🙂

**Comment by abiaad** [comment]
You already support it 👍  I've just added specs in your readme and created a pull a request . I'm closing this issue and waiting your feedback on my PR 😉
