### ISSUE TITLE
Range<Index> init issue

### ISSUE THREAD

**Issue by ludoded** [krisk/fuse-swift#9]
In the latest Xcode 10, there is an issue with Range<Index> initializer, which corresponds to new changes in Swift 4.2

<img width="851" alt="2018-06-05 14 28 28" src="https://user-images.githubusercontent.com/4401289/40973407-c957b1cc-68cc-11e8-98e4-175842861b86.png">

**Comment by jlaws** [comment]
Any update on this?  The XCode 10 GM is out so adding Swift 4.2 support is needed.  Thanks for the great library!

**Comment by jlaws** [comment]
Works great, thank you!
